name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}  
        run: |
          pytest tests/  

  static-analysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          pylint app.py tests/test_app.py

  dynamic-analysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start application
        run: |
          nohup python app.py &  # Start your Flask app in the background

      - name: Run OWASP ZAP scan (using Docker)
        run: |
          docker run --rm -d --name zap \
            -p 8080:8080 \
            owasp/zap2docker-stable:latest zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true

      - name: Wait for ZAP to start
        run: |
          sleep 30  # Adjust this time as necessary for ZAP to start up

      - name: Run scan against the application
        run: |
          curl --proxy http://localhost:8080 http://localhost:5000 > zap_scan_report.txt

      - name: Stop OWASP ZAP container
        run: |
          docker stop zap
