name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install flask

      - name: Run tests (add your test command here)
        run: |
          echo "Running tests..."

  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  

      - name: Install SonarQube scanner
        uses: nosinovacao/sonarscanner-action@v1
        with:
          version: '6.1.0.4477'
          javaDistribution: 'temurin'
          javaVersion: '11' 

      - name: Run SonarQube analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-app \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}


  dynamic-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP (configure ZAP)
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:5000 -r zap_report.html 
